Hw05 parallel execution
uralmetal/hw_golang_otus pull request #6
Opened 2023-12-24 06:33 UTC by uralmetal

## Домашнее задание №5 «Параллельное исполнение»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - run.go ~55 строк

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-12-24 15:20 UTC, ityulkanov requested changes
Рекомендую переписать логику на работу с каналом, будет намного легче, в остальном всё почти так)

2023-12-24 15:20 UTC, ityulkanov commented on hw05_parallel_execution/run.go
> +	}
Я так понимаю вы таким образом решили как раздавать таски равномерно, но тут есть более удобное решение, для которого собственно эта задача и создавалась ,один из примитивов синхронизации - канал вам подойдет тут намного больше. Попробуйте переписать логику на работу с каналом, и создавать количество корутин == n

2023-12-25 05:36 UTC, uralmetal commented on hw05_parallel_execution/run.go
> +	}
да, всё так. Исправил на каналы

2023-12-25 09:52 UTC, ityulkanov approved these changes

2023-12-25 09:52 UTC, ityulkanov commented on hw05_parallel_execution/run.go
> +	}
Достаточно будет вот тут, в момент загрузки проверять ваш каунтер, что он не превышен. Ну  и саму загрузку проводить уже после того как у вас горутины развёрнуты в боевое положение)

2023-12-25 09:52 UTC, ityulkanov commented on hw05_parallel_execution/run.go
> +	workersTasks := make(chan Task, len(tasks))
В принципе вам тут не нужен буферизованный канал, если вы будете не уменьшать количество ошибок в каунтере а увеличивать

2023-12-25 09:52 UTC, ityulkanov commented on hw05_parallel_execution/run.go
> +	if errorCount <= 0 {
тогда тут останется только проверить что errCount <= m

2023-12-25 09:52 UTC, merged